termos = int(input("Quantos termos você quer mostrar? "))
primeiro_termo = 0
segundo_termo = 1
print(f"{primeiro_termo} -> {segundo_termo}", end=' ')
contador = 3
while contador <= termos:
    terceiro_termo = primeiro_termo + segundo_termo
    print(f" -> {terceiro_termo}", end='')
    primeiro_termo = segundo_termo
    segundo_termo = terceiro_termo
    contador += 1