valor = input('Digite algo para eu analisar:')
print('O tipo primitivo desse dado é:', type(valor))
print('É alfabetico? ' ,valor.isalpha())
print('É um número? ',valor.isnumeric())
print('Só tem espaços? ',valor.isspace())
print('É alphanumérico? ',valor.isalnum())
print('Está em caixa alta? ',valor.isupper())
print('Está em caixa baixa? ',valor.islower())
print('A primeira letra está em maiúsculo?',valor.istitle())
