nome = str(input('Qual o seu nome completo? '))
valor = nome.split()
print('Muito prazer em te conheecer!')
print(f'Seu primeiro nome é {valor[0]}.')
print(f'Seu último nome é {valor[len(valor)-1]}.')