nome = str(input("Qual o seu nome completo? "))
print(f"Seu nome com todas as letras em maiúsculo fica: {nome.upper()}")
print(f"Seu nome em minúsculo fica: {nome.lower()}")
print(f"Seu nome sem espaços tem {len(nome)-nome.count(' ')} letras.")
separado = nome.split()
print(f"Seu primeiro nome {separado[0]}  tem {len(separado[0])} letras.")